import { openDB, type DBSchema, type IDBPDatabase } from 'idb'
import type { Photo, ProcessingSession, FaceCluster } from './types'

interface AppDB extends DBSchema {
  photos: {
    key: string // photo id
    value: Photo
    indexes: { 'by-session': string; 'by-timestamp': number; 'by-hash': string }
  }
  sessions: {
    key: string // session id
    value: ProcessingSession
  }
  clusters: {
    key: string // cluster id
    value: FaceCluster
  }
}

const DB_NAME = 'photo-selector-db'
const DB_VERSION = 2

let dbPromise: Promise<IDBPDatabase<AppDB>>

export function getDB() {
  if (!dbPromise) {
    dbPromise = openDB<AppDB>(DB_NAME, DB_VERSION, {
      upgrade(db, oldVersion, newVersion, transaction) {
        if (!db.objectStoreNames.contains('photos')) {
          const store = db.createObjectStore('photos', { keyPath: 'id' })
          store.createIndex('by-session', 'sessionId') // Make sure Photo has sessionId
          store.createIndex('by-timestamp', 'timestamp')
          store.createIndex('by-hash', 'hash')
        } else {
          // Migration for existing DB
          const store = transaction.objectStore('photos')
          if (!store.indexNames.contains('by-hash')) {
            store.createIndex('by-hash', 'hash')
          }
        }
        if (!db.objectStoreNames.contains('sessions')) {
          db.createObjectStore('sessions', { keyPath: 'id' })
        }
        if (!db.objectStoreNames.contains('clusters')) {
          db.createObjectStore('clusters', { keyPath: 'id' })
        }
      },
    })
  }
  return dbPromise
}

export async function savePhoto(photo: Photo) {
  const db = await getDB()
  return db.put('photos', photo)
}

export async function getPhotosBySession(sessionId: string) {
  const db = await getDB()
  // We need to add sessionId to Photo interface in types.ts first if we want to index by it.
  // Assuming we filter manually or add index.
  // For now, let's just get all and filter or use cursor.
  // Actually, let's update Photo interface later or now.
  // But wait, getAllFromIndex is better.
  // We will assume Photo has a sessionId field.
  return db.getAllFromIndex('photos', 'by-session', sessionId)
}

export async function getPhotoByHash(hash: string): Promise<Photo | undefined> {
  const db = await getDB()
  return db.getFromIndex('photos', 'by-hash', hash)
}

export async function getPhoto(id: string) {
  const db = await getDB()
  return db.get('photos', id)
}

export async function saveSession(session: ProcessingSession) {
  const db = await getDB()
  return db.put('sessions', session)
}

export async function getSession(id: string) {
  const db = await getDB()
  return db.get('sessions', id)
}

export async function saveCluster(cluster: FaceCluster) {
  const db = await getDB()
  return db.put('clusters', cluster)
}

export async function getAllClusters(): Promise<FaceCluster[]> {
  const db = await getDB()
  return db.getAll('clusters')
}

export async function deleteCluster(id: string): Promise<void> {
  const db = await getDB()
  await db.delete('clusters', id)
}

export async function updateClusterLabel(id: string, label: string) {
  const db = await getDB()
  const cluster = await db.get('clusters', id)
  if (cluster) {
    cluster.label = label
    return db.put('clusters', cluster)
  }
}

export async function clearExistingData() {
  console.log('Clearing existing data...')
  const db = await getDB()
  await db.clear('photos')
  await db.clear('sessions')
  await db.clear('clusters')
  console.log('Existing data cleared.')
}

export async function clearPhotos() {
  console.log('Clearing photos only...')
  const db = await getDB()

  // 1. Clear Photo and Session stores
  await db.clear('photos')
  await db.clear('sessions')

  // 2. Handle clusters:
  //    - DELETE auto-generated clusters (default "Person X" labels)
  //      to prevent stale clusters from competing with trained ones on next upload
  //    - KEEP user-trained clusters (custom labels) but reset their photo lists
  const clusters = await db.getAll('clusters')
  const tx = db.transaction('clusters', 'readwrite')
  const store = tx.objectStore('clusters')

  const isAutoGenerated = (label: string) => /^(Person|人物) \d+$/.test(label)

  await Promise.all(
    clusters.map((cluster) => {
      if (isAutoGenerated(cluster.label)) {
        return store.delete(cluster.id)
      }
      // Reset photo lists for user-trained clusters
      cluster.photoIds = []
      cluster.confirmedPhotoIds = []
      return store.put(cluster)
    }),
  )

  await tx.done
  console.log('Photos, sessions cleared. Auto-generated clusters deleted, trained clusters reset.')
}

export async function getLastSession(): Promise<ProcessingSession | undefined> {
  const db = await getDB()
  const sessions = await db.getAll('sessions')
  if (sessions.length === 0) return undefined
  return sessions.reduce((latest, current) => {
    return latest.updatedAt > current.updatedAt ? latest : current
  })
}

